apiVersion: v1
kind: Pod
metadata:
  name: rag-playground
  namespace: rag-sample-nvaie
spec:
  containers:
  - command:
    - python3.10
    - -m
    - frontend
    - --port
    - "8090"
    env:
    - name: APP_MODELNAME
      value: llama-2-7b-chat-hf
    - name: APP_SERVERPORT
      value: "8081"
    - name: APP_SERVERURL
      value: http://chain-server
    - name: RIVA_API_URI
    - name: RIVA_API_KEY
    - name: RIVA_FUNCTION_ID
    - name: TTS_SAMPLE_RATE
      value: "48000"
    image: nvcr.io/ohlfw0olaadg/ea-rag-examples/rag-playground:0.5.0-rc1
    imagePullPolicy: IfNotPresent
    name: rag-playground
    ports:
    - containerPort: 8090
      name: http
      protocol: TCP
    resources: {}
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: kube-api-access-cdfwr
      readOnly: true
  dnsPolicy: ClusterFirst
  enableServiceLinks: true
  imagePullSecrets:
  - name: ngc-secret
  nodeName: dgx-a100-3
  preemptionPolicy: PreemptLowerPriority
  priority: 0
            path: ca.crt
  schedulerName: default-scheduler
  securityContext: {}
  serviceAccount: default
  serviceAccountName: default
  terminationGracePeriodSeconds: 30
  tolerations:
  - effect: NoExecute
    key: node.kubernetes.io/not-ready
    operator: Exists
    tolerationSeconds: 300
  - effect: NoExecute
    key: node.kubernetes.io/unreachable
    operator: Exists
    tolerationSeconds: 300
  volumes:
  - name: eng-data
    hostPath:
      path: /mnt/eng_data/datasets/
      type: Directory
    mountPath: /mnt/nfs
  - name: kube-api-access-cdfwr
    projected:
      defaultMode: 420
      sources:
      - serviceAccountToken:
          path: token
      - configMap:
          items:
          - key: ca.crt
            path: ca.crt
          name: kube-root-ca.crt
      - downwardAPI:
          items:
          - fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
            path: namespace
