# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: relations.proto
# Protobuf Python Version: 5.28.3
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    28,
    3,
    '',
    'relations.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0frelations.proto\x12\x1a\x63om.nvidia.rapids.ml.proto\"g\n\x0eTuningRelation\x12\x44\n\x02\x63v\x18\x01 \x01(\x0b\x32\x32.com.nvidia.rapids.ml.proto.CrossValidatorRelationH\x00R\x02\x63vB\x0f\n\rrelation_type\"\xbb\x02\n\x16\x43rossValidatorRelation\x12\x10\n\x03uid\x18\x01 \x01(\tR\x03uid\x12\x44\n\testimator\x18\x02 \x01(\x0b\x32&.com.nvidia.rapids.ml.proto.MlOperatorR\testimator\x12\x30\n\x14\x65stimator_param_maps\x18\x03 \x01(\tR\x12\x65stimatorParamMaps\x12\x44\n\tevaluator\x18\x04 \x01(\x0b\x32&.com.nvidia.rapids.ml.proto.MlOperatorR\tevaluator\x12\x1b\n\x06params\x18\x05 \x01(\tH\x00R\x06params\x88\x01\x01\x12\x1d\n\x07\x64\x61taset\x18\x06 \x01(\x0cH\x01R\x07\x64\x61taset\x88\x01\x01\x42\t\n\x07_paramsB\n\n\x08_dataset\"\xc5\x02\n\nMlOperator\x12\x12\n\x04name\x18\x01 \x01(\tR\x04name\x12\x10\n\x03uid\x18\x02 \x01(\tR\x03uid\x12G\n\x04type\x18\x03 \x01(\x0e\x32\x33.com.nvidia.rapids.ml.proto.MlOperator.OperatorTypeR\x04type\x12\x1b\n\x06params\x18\x04 \x01(\tH\x00R\x06params\x88\x01\x01\"\x9f\x01\n\x0cOperatorType\x12\x1d\n\x19OPERATOR_TYPE_UNSPECIFIED\x10\x00\x12\x1b\n\x17OPERATOR_TYPE_ESTIMATOR\x10\x01\x12\x1d\n\x19OPERATOR_TYPE_TRANSFORMER\x10\x02\x12\x1b\n\x17OPERATOR_TYPE_EVALUATOR\x10\x03\x12\x17\n\x13OPERATOR_TYPE_MODEL\x10\x04\x42\t\n\x07_paramsB!\n\x1a\x63om.nvidia.rapids.ml.protoP\x01\xa0\x01\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'relations_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\032com.nvidia.rapids.ml.protoP\001\240\001\001'
  _globals['_TUNINGRELATION']._serialized_start=47
  _globals['_TUNINGRELATION']._serialized_end=150
  _globals['_CROSSVALIDATORRELATION']._serialized_start=153
  _globals['_CROSSVALIDATORRELATION']._serialized_end=468
  _globals['_MLOPERATOR']._serialized_start=471
  _globals['_MLOPERATOR']._serialized_end=796
  _globals['_MLOPERATOR_OPERATORTYPE']._serialized_start=626
  _globals['_MLOPERATOR_OPERATORTYPE']._serialized_end=785
# @@protoc_insertion_point(module_scope)
