/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_nvidia_spark_ml_linalg_JniCUBLAS */

#ifndef _Included_com_nvidia_spark_ml_linalg_JniCUBLAS
#define _Included_com_nvidia_spark_ml_linalg_JniCUBLAS
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_nvidia_spark_ml_linalg_JniCUBLAS
 * Method:    dspr
 * Signature: (I[D[D)V
 */
JNIEXPORT void JNICALL Java_com_nvidia_spark_ml_linalg_JniCUBLAS_dspr
  (JNIEnv *, jobject, jint, jdoubleArray, jdoubleArray);

/*
 * Class:     com_nvidia_spark_ml_linalg_JniCUBLAS
 * Method:    dgemm
 * Signature: (II[D[DI)V
 */
JNIEXPORT void JNICALL Java_com_nvidia_spark_ml_linalg_JniCUBLAS_dgemm
  (JNIEnv *, jobject, jint, jint, jdoubleArray, jdoubleArray, jint);

/*
 * Class:     com_nvidia_spark_ml_linalg_JniCUBLAS
 * Method:    dgemm_b
 * Signature: (III[D[D[DI)V
 */
JNIEXPORT void JNICALL Java_com_nvidia_spark_ml_linalg_JniCUBLAS_dgemm_1b
  (JNIEnv *, jobject, jint, jint, jint, jdoubleArray, jdoubleArray, jdoubleArray, jint);

/*
 * Class:     com_nvidia_spark_ml_linalg_JniCUBLAS
 * Method:    cusolverDnDgesvd
 * Signature: (I[D[D[DI)V
 */
JNIEXPORT void JNICALL Java_com_nvidia_spark_ml_linalg_JniCUBLAS_cusolverDnDgesvd
  (JNIEnv *, jobject, jint, jdoubleArray, jdoubleArray, jdoubleArray, jint);

/*
 * Class:     com_nvidia_spark_ml_linalg_JniCUBLAS
 * Method:    eigDC
 * Signature: (I[D[D[DI)V
 */
JNIEXPORT void JNICALL Java_com_nvidia_spark_ml_linalg_JniCUBLAS_eigDC
  (JNIEnv *, jobject, jint, jdoubleArray, jdoubleArray, jdoubleArray, jint);

#ifdef __cplusplus
}
#endif
#endif
